version = 0.1
[default.deploy.parameters]
stack_name = "bedrock-agent"
resolve_s3 = true
s3_prefix = "bedrock-agent"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev\""
template = "template-agents.yaml"
image_repositories = []
