version = 0.1
[default.deploy.parameters]
stack_name = "bedrock-agent-lambda"
resolve_s3 = true
s3_prefix = "bedrock-agent-lambda"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev\" AgentsStackName=\"bedrock-agent\""
template = "template-lambda.yaml"
image_repositories = []
