default_agent: hr_agent_agentcore
agents:
  hr_agent_agentcore:
    name: hr_agent_agentcore
    entrypoint: hr_agent.py
    platform: linux/arm64
    container_runtime: docker
    aws:
      execution_role: arn:aws:iam::479047237979:role/hr-agents-agentcore-role-agentcore
      execution_role_auto_create: true
      account: '479047237979'
      region: us-east-1
      ecr_repository: 479047237979.dkr.ecr.us-east-1.amazonaws.com/hr-agent-agentcore
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: hr_agent_agentcore-uyOKxJ2cAL
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:479047237979:runtime/hr_agent_agentcore-uyOKxJ2cAL
      agent_session_id: 08f73635-dae3-4123-9e3f-f911cf4ace28
    codebuild:
      project_name: bedrock-agentcore-hr_agent_agentcore-builder
      execution_role: arn:aws:iam::479047237979:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-6275474ecf
      source_bucket: bedrock-agentcore-codebuild-sources-479047237979-us-east-1
    authorizer_configuration: null
    oauth_configuration: null
